### PR TITLE
fix: change default HD path to `m/44'/1'/0'/0`

### PR DESCRIPTION
**Pull request by merc1er**
### What I did

fixes: #24

Trezor does not let us use the default Ethereum derivation path by default ([source](https://github.com/trezor/trezor-firmware/issues/1336#issuecomment-720126545)). 

### How to verify it

1. Plug in a Trezor
2. Check its Ethereum address in Trezor Suite
3. Add the Trezor account to ape:  `ape trezor add trezor`
4. Check that the address of index `0` is different from the address found in Trezor suite.

### Checklist

- [ ] Passes all linting checks (pre-commit and CI jobs)
- [ ] New test cases have been added and are passing
- [ ] Documentation has been updated
- [ ] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standard (will be automatically included in the changelog)

### CODE REVIEW

**Review by unparalleled-js — APPROVED** [review]
Makes sense to me, based on the comment linked in the issue regarding the security practices of the device.

I am going to do some testing and yet and gather more insight.

**Comment by unparalleled-js** [comment]
for some reason, my Trezor Suite accounts use `m/44'/60'/0'/0/0` and I am trying to figure out why

**Comment by NotPeopling2day** [comment]
Looks like for Ethereum | 44'/c'/0'/0/a
https://docs.trezor.io/trezor-firmware/misc/coins-bip44-paths.html

with `c` being the [SLIP-44 id](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

**Comment by unparalleled-js** [comment]
> Looks like for Ethereum | 44'/c'/0'/0/a https://docs.trezor.io/trezor-firmware/misc/coins-bip44-paths.html
> 
> with `c` being the [SLIP-44 id](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

Yes, this is aligns with what I am seeing on trezor suite for all my test devices. I am still looking into the txn signing error though. I think I found the culprit, which would explain all of this. Standby!

**Comment by unparalleled-js** [comment]
@fubuloubu I saw you approve my other Trezor PR for getting accounts off the default HD path working, but wondering your thoughts on also doing this? By changing the default, we can discourage the use of bypassing security measures and have a better experience without requiring changing the HD Path.

**Comment by fubuloubu** [comment]
> @fubuloubu I saw you approve my other Trezor PR for getting accounts off the default HD path working, but wondering your thoughts on also doing this? By changing the default, we can discourage the use of bypassing security measures and have a better experience without requiring changing the HD Path.

Yes, was just thinking that reviewing the answer

Having to specify a different one just once would be a suitable alternative. Just mention it in the docs.

**Comment by unparalleled-js** [comment]
> Having to specify a different one just once would be a suitable alternative. Just mention it in the docs.

I had the same thought and that was the inspiration for this PR here: https://github.com/ApeWorX/ape-trezor/pull/30
where you can configure the HD Path in the `ape-config.yaml` file just once.

The issue with that is that is project-based, and something like that makes more sense at the global-config level.

https://github.com/ApeWorX/ape/issues/379

**Pull request closed without merging**
